version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - postgres
    volumes:
      - .:/app

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
